services:
  cartx-client:
    build: cartx-client # Path to the Dockerfile
    image: cartx-client:latest # Name of the image
    container_name: cartx-client # Name of the container
    ports:
      - "8080:80"
    volumes:
      - ./cartx-client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000
    networks:
      - cartx-network
  cartx-product-service:
    build: cartx-services/product-service
    image: cartx-product-service:latest
    container_name: cartx-product-service
    volumes:
      - ./cartx-services/product-service:/src
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
    - DOTNET_USE_POLLING_FILE_WATCHER=1
    command: dotnet watch --project product-service run --no-launch-profile
    ports:
      - "8081:80"
    networks:
      - cartx-network

networks:
  cartx-network:
    driver: bridge
