services:
  cartx-client:
    build: cartx-client
    container_name: cartx-client
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - cartx-network
  cartx-product-service:
    build: cartx-services/product-service
    container_name: cartx-product-service
    ports:
      - "8081:80"
    networks:
      - cartx-network

networks:
  cartx-network:
    driver: bridge
