FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --frozen-lockfile

COPY . .

RUN npm run build -- --configuration=production

FROM nginx:stable-alpine AS runner

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist/cartx-client/browser/ ./

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]